apiVersion: apps/v1
kind: Deployment
metadata:
  name: hz-kube-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hz-kube
  template:
    metadata:
      labels:
        app: hz-kube
    spec:
      containers:
        - name: hz-kube
          image: prasadct/hz-kube:v6
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: hz-kube-service
spec:
  type: NodePort
  selector:
    app: hz-kube
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
